<Project Sdk="Microsoft.NET.Sdk.Worker">

  <ItemGroup>
    <ProjectReference Include="..\UBS.AM.PLT.Snapshot.Application\UBS.AM.PLT.Snapshot.Application.csproj" />
    <ProjectReference Include="..\UBS.AM.PLT.Snapshot.Infrastructure\Sql\UBS.AM.PLT.Snapshot.Infrastructure.Sql.csproj" />
    <ProjectReference Include="..\UBS.AM.PLT.Snapshot.Infrastructure\Adls\UBS.AM.PLT.Snapshot.Infrastructure.Adls.csproj" />
    <ProjectReference Include="..\UBS.AM.PLT.Snapshot.Infrastructure\Kafka\UBS.AM.PLT.Snapshot.Infrastructure.Kafka.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

</Project>
