<Project Sdk="Microsoft.NET.Sdk.Worker">

  <ItemGroup>
    <ProjectReference Include="..\UBS.AM.PLT.SnapshotWriter.Application\UBS.AM.PLT.SnapshotWriter.Application.csproj" />
    <ProjectReference Include="..\UBS.AM.PLT.SnapshotWriter.Infrastructure\UBS.AM.PLT.SnapshotWriter.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>

</Project>
