<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\UBS.AM.PLT.Snapshot.Application\UBS.AM.PLT.Snapshot.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Sql\UBS.AM.PLT.Snapshot.Infrastructure.Sql.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Adls\UBS.AM.PLT.Snapshot.Infrastructure.Adls.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Kafka\UBS.AM.PLT.Snapshot.Infrastructure.Kafka.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="LiveTesting\Data\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
